[tool.poetry]
name = "job-executor"
version = "0.1.0"
description = ""
authors = ["Microdata Developers <microdata-dev@ssb.no>"]

[tool.poetry.dependencies]
python = "^3.9"
pyarrow = "8.0.0"
microdata-validator = "^7.3.3"
pydantic = "^1.9.1"
requests = "^2.28.0"
requests-mock = "^1.9.3"
pandas = "^1.4.2"
pyhumps = "^3.7.2"
json-logging = "^1.3.0"
tomlkit = "^0.11.4"

[tool.poetry.group.dev.dependencies]
pylint = "^2.17.3"
pytest = "^7.1.2"
pytest-dotenv = "^0.5.2"
pytest-cov = "^3.0.0"
pycodestyle = "^2.8.0"
pytest-mock = "^3.8.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
