[tool.poetry]
name = "job-executor"
version = "0.1.0"
description = ""
authors = ["Microdata Developers <microdata-dev@ssb.no>"]

[tool.poetry.dependencies]
python = "^3.13"
pyarrow = "^21.0.0"
pydantic = "^2.6.1"
requests = "^2.32.4"
pandas = "^2.2.1"
urllib3 = "^2.5.0"
microdata-tools = "1.10.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.1"
pytest-dotenv = "^0.5.2"
pytest-cov = "^6.0.0"
requests-mock = "^1.9.3"
pytest-mock = "^3.8.2"
ruff = "^0.11.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 79
target-version = "py312"