[tool.poetry]
name = "job-executor"
version = "0.1.0"
description = ""
authors = ["Microdata Developers <microdata-dev@ssb.no>"]

[tool.poetry.dependencies]
python = "^3.9"
pyarrow = "12.0.1"
pydantic = "^1.9.1"
requests = "^2.31.0"
requests-mock = "^1.9.3"
pandas = "^1.4.2"
pyhumps = "^3.7.2"
json-logging = "^1.3.0"
tomlkit = "^0.11.4"
microdata-tools = "^0.7.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"
pytest-dotenv = "^0.5.2"
pytest-cov = "^3.0.0"
pytest-mock = "^3.8.2"
black = "^23.3.0"
ruff = "^0.0.269"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79